/*
 * This file is generated by jOOQ.
 */
package io.github.lionstats.db.postgresql.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationUser implements Serializable {

    private static final long serialVersionUID = 1214219492;

    private final Long          id;
    private final String        email;
    private final String        username;
    private final byte[]        password;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;
    private final LocalDateTime lastLoggedIn;

    public ApplicationUser(ApplicationUser value) {
        this.id = value.id;
        this.email = value.email;
        this.username = value.username;
        this.password = value.password;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.lastLoggedIn = value.lastLoggedIn;
    }

    public ApplicationUser(
        Long          id,
        String        email,
        String        username,
        byte[]        password,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        LocalDateTime lastLoggedIn
    ) {
        this.id = id;
        this.email = email;
        this.username = username;
        this.password = password;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.lastLoggedIn = lastLoggedIn;
    }

    public Long getId() {
        return this.id;
    }

    public String getEmail() {
        return this.email;
    }

    public String getUsername() {
        return this.username;
    }

    public byte[] getPassword() {
        return this.password;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public LocalDateTime getLastLoggedIn() {
        return this.lastLoggedIn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplicationUser (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(username);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(lastLoggedIn);

        sb.append(")");
        return sb.toString();
    }
}
