/*
 * This file is generated by jOOQ.
 */
package io.github.lionstats.db.postgresql.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildWarsApiKey implements Serializable {

    private static final long serialVersionUID = 1358889959;

    private final Long          id;
    private final Long          applicationUserId;
    private final String        apiKey;
    private final String        name;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;
    private final LocalDateTime lastUsed;

    public GuildWarsApiKey(GuildWarsApiKey value) {
        this.id = value.id;
        this.applicationUserId = value.applicationUserId;
        this.apiKey = value.apiKey;
        this.name = value.name;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.lastUsed = value.lastUsed;
    }

    public GuildWarsApiKey(
        Long          id,
        Long          applicationUserId,
        String        apiKey,
        String        name,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        LocalDateTime lastUsed
    ) {
        this.id = id;
        this.applicationUserId = applicationUserId;
        this.apiKey = apiKey;
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.lastUsed = lastUsed;
    }

    public Long getId() {
        return this.id;
    }

    public Long getApplicationUserId() {
        return this.applicationUserId;
    }

    public String getApiKey() {
        return this.apiKey;
    }

    public String getName() {
        return this.name;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public LocalDateTime getLastUsed() {
        return this.lastUsed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GuildWarsApiKey (");

        sb.append(id);
        sb.append(", ").append(applicationUserId);
        sb.append(", ").append(apiKey);
        sb.append(", ").append(name);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(lastUsed);

        sb.append(")");
        return sb.toString();
    }
}
