/*
 * This file is generated by jOOQ.
 */
package io.github.lionstats.db.postgresql.tables;


import io.github.lionstats.db.postgresql.Indexes;
import io.github.lionstats.db.postgresql.Keys;
import io.github.lionstats.db.postgresql.Public;
import io.github.lionstats.db.postgresql.tables.records.ApplicationUserRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationUser extends TableImpl<ApplicationUserRecord> {

    private static final long serialVersionUID = -1085416313;

    /**
     * The reference instance of <code>public.application_user</code>
     */
    public static final ApplicationUser APPLICATION_USER = new ApplicationUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplicationUserRecord> getRecordType() {
        return ApplicationUserRecord.class;
    }

    /**
     * The column <code>public.application_user.id</code>.
     */
    public final TableField<ApplicationUserRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('application_user_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.application_user.email</code>.
     */
    public final TableField<ApplicationUserRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.application_user.username</code>.
     */
    public final TableField<ApplicationUserRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>public.application_user.password</code>.
     */
    public final TableField<ApplicationUserRecord, byte[]> PASSWORD = createField(DSL.name("password"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.application_user.created_at</code>.
     */
    public final TableField<ApplicationUserRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.application_user.updated_at</code>.
     */
    public final TableField<ApplicationUserRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.application_user.last_logged_in</code>.
     */
    public final TableField<ApplicationUserRecord, LocalDateTime> LAST_LOGGED_IN = createField(DSL.name("last_logged_in"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>public.application_user</code> table reference
     */
    public ApplicationUser() {
        this(DSL.name("application_user"), null);
    }

    /**
     * Create an aliased <code>public.application_user</code> table reference
     */
    public ApplicationUser(String alias) {
        this(DSL.name(alias), APPLICATION_USER);
    }

    /**
     * Create an aliased <code>public.application_user</code> table reference
     */
    public ApplicationUser(Name alias) {
        this(alias, APPLICATION_USER);
    }

    private ApplicationUser(Name alias, Table<ApplicationUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private ApplicationUser(Name alias, Table<ApplicationUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> ApplicationUser(Table<O> child, ForeignKey<O, ApplicationUserRecord> key) {
        super(child, key, APPLICATION_USER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UNIQUE_EMAIL_INDEX, Indexes.UNIQUE_USERNAME_INDEX);
    }

    @Override
    public Identity<ApplicationUserRecord, Long> getIdentity() {
        return Keys.IDENTITY_APPLICATION_USER;
    }

    @Override
    public UniqueKey<ApplicationUserRecord> getPrimaryKey() {
        return Keys.APPLICATION_USER_PKEY;
    }

    @Override
    public List<UniqueKey<ApplicationUserRecord>> getKeys() {
        return Arrays.<UniqueKey<ApplicationUserRecord>>asList(Keys.APPLICATION_USER_PKEY);
    }

    @Override
    public ApplicationUser as(String alias) {
        return new ApplicationUser(DSL.name(alias), this);
    }

    @Override
    public ApplicationUser as(Name alias) {
        return new ApplicationUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationUser rename(String name) {
        return new ApplicationUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationUser rename(Name name) {
        return new ApplicationUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, byte[], LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
