/*
 * This file is generated by jOOQ.
 */
package io.github.lionstats.db.postgresql;


import io.github.lionstats.db.postgresql.tables.ApplicationUser;
import io.github.lionstats.db.postgresql.tables.FlywaySchemaHistory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UNIQUE_EMAIL_INDEX = Indexes0.UNIQUE_EMAIL_INDEX;
    public static final Index UNIQUE_USERNAME_INDEX = Indexes0.UNIQUE_USERNAME_INDEX;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index UNIQUE_EMAIL_INDEX = Internal.createIndex("unique_email_index", ApplicationUser.APPLICATION_USER, new OrderField[] { ApplicationUser.APPLICATION_USER.EMAIL }, true);
        public static Index UNIQUE_USERNAME_INDEX = Internal.createIndex("unique_username_index", ApplicationUser.APPLICATION_USER, new OrderField[] { ApplicationUser.APPLICATION_USER.USERNAME }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    }
}
