/*
 * This file is generated by jOOQ.
 */
package io.github.lionstats.db.postgresql;


import io.github.lionstats.db.postgresql.tables.ApplicationUser;
import io.github.lionstats.db.postgresql.tables.FlywaySchemaHistory;
import io.github.lionstats.db.postgresql.tables.GuildWarsApiKey;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1361450410;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.application_user</code>.
     */
    public final ApplicationUser APPLICATION_USER = ApplicationUser.APPLICATION_USER;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.guild_wars_api_key</code>.
     */
    public final GuildWarsApiKey GUILD_WARS_API_KEY = GuildWarsApiKey.GUILD_WARS_API_KEY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.APPLICATION_USER_ID_SEQ,
            Sequences.GUILD_WARS_API_KEY_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            ApplicationUser.APPLICATION_USER,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            GuildWarsApiKey.GUILD_WARS_API_KEY);
    }
}
