/*
 * This file is generated by jOOQ.
 */
package io.github.lionstats.db.postgresql;


import io.github.lionstats.db.postgresql.tables.ApplicationUser;
import io.github.lionstats.db.postgresql.tables.FlywaySchemaHistory;
import io.github.lionstats.db.postgresql.tables.GuildWarsApiKey;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.application_user</code>.
     */
    public static final ApplicationUser APPLICATION_USER = ApplicationUser.APPLICATION_USER;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.guild_wars_api_key</code>.
     */
    public static final GuildWarsApiKey GUILD_WARS_API_KEY = GuildWarsApiKey.GUILD_WARS_API_KEY;
}
